version: '3'
services:
    php:
        build:
            context: ./docker-files/runtimes/php8.1
            dockerfile: Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        restart: unless-stopped
        container_name: php-${ENVIRONMENT}
        tty: true
        links:
            - mysql
        volumes:
            - ./:/var/www/html
            - ./docker-files/runtimes/php8.1/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - ${ENVIRONMENT}
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        container_name: nginx-${ENVIRONMENT}
        ports:
            - '${NGINX_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
            - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/
        links:
            - php
            - phpmyadmin
        depends_on:
            - php
            - mysql
        networks:
            - ${ENVIRONMENT}
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        env_file:
            - ".env"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        container_name: mysql-${ENVIRONMENT}
        volumes:
            - 'mysql-${ENVIRONMENT}:/var/lib/mysql'
        networks:
            - ${ENVIRONMENT}
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin-${ENVIRONMENT}
        ports:
            - '${PHPMYADMIN_PORT:-8080}:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        networks:
            - ${ENVIRONMENT}
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        container_name: redis-${ENVIRONMENT}
        volumes:
            - 'redis-${ENVIRONMENT}:/data'
        networks:
            - ${ENVIRONMENT}
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
    master:
        driver: bridge
    develop:
        driver: bridge
volumes:
    mysql-master:
        driver: local
    mysql-develop:
        driver: local
    redis-master:
        driver: local
    redis-develop:
        driver: local
